/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package everfeeds.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ApplicationAPI {

  public interface Iface {

    public Token createToken(String applicationSecret, String accountId) throws org.apache.thrift.TException;

    public Account createAccessAndAccount(String applicationSecret, Access access, String accessToken, String accessSecret, String accessShardId) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void createToken(String applicationSecret, String accountId, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.createToken_call> resultHandler) throws org.apache.thrift.TException;

    public void createAccessAndAccount(String applicationSecret, Access access, String accessToken, String accessSecret, String accessShardId, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.createAccessAndAccount_call> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client implements org.apache.thrift.TServiceClient, Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      this(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot)
    {
      iprot_ = iprot;
      oprot_ = oprot;
    }

    protected org.apache.thrift.protocol.TProtocol iprot_;
    protected org.apache.thrift.protocol.TProtocol oprot_;

    protected int seqid_;

    public org.apache.thrift.protocol.TProtocol getInputProtocol()
    {
      return this.iprot_;
    }

    public org.apache.thrift.protocol.TProtocol getOutputProtocol()
    {
      return this.oprot_;
    }

    public Token createToken(String applicationSecret, String accountId) throws org.apache.thrift.TException
    {
      send_createToken(applicationSecret, accountId);
      return recv_createToken();
    }

    public void send_createToken(String applicationSecret, String accountId) throws org.apache.thrift.TException
    {
      oprot_.writeMessageBegin(new org.apache.thrift.protocol.TMessage("createToken", org.apache.thrift.protocol.TMessageType.CALL, ++seqid_));
      createToken_args args = new createToken_args();
      args.setApplicationSecret(applicationSecret);
      args.setAccountId(accountId);
      args.write(oprot_);
      oprot_.writeMessageEnd();
      oprot_.getTransport().flush();
    }

    public Token recv_createToken() throws org.apache.thrift.TException
    {
      org.apache.thrift.protocol.TMessage msg = iprot_.readMessageBegin();
      if (msg.type == org.apache.thrift.protocol.TMessageType.EXCEPTION) {
        org.apache.thrift.TApplicationException x = org.apache.thrift.TApplicationException.read(iprot_);
        iprot_.readMessageEnd();
        throw x;
      }
      if (msg.seqid != seqid_) {
        throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.BAD_SEQUENCE_ID, "createToken failed: out of sequence response");
      }
      createToken_result result = new createToken_result();
      result.read(iprot_);
      iprot_.readMessageEnd();
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "createToken failed: unknown result");
    }

    public Account createAccessAndAccount(String applicationSecret, Access access, String accessToken, String accessSecret, String accessShardId) throws org.apache.thrift.TException
    {
      send_createAccessAndAccount(applicationSecret, access, accessToken, accessSecret, accessShardId);
      return recv_createAccessAndAccount();
    }

    public void send_createAccessAndAccount(String applicationSecret, Access access, String accessToken, String accessSecret, String accessShardId) throws org.apache.thrift.TException
    {
      oprot_.writeMessageBegin(new org.apache.thrift.protocol.TMessage("createAccessAndAccount", org.apache.thrift.protocol.TMessageType.CALL, ++seqid_));
      createAccessAndAccount_args args = new createAccessAndAccount_args();
      args.setApplicationSecret(applicationSecret);
      args.setAccess(access);
      args.setAccessToken(accessToken);
      args.setAccessSecret(accessSecret);
      args.setAccessShardId(accessShardId);
      args.write(oprot_);
      oprot_.writeMessageEnd();
      oprot_.getTransport().flush();
    }

    public Account recv_createAccessAndAccount() throws org.apache.thrift.TException
    {
      org.apache.thrift.protocol.TMessage msg = iprot_.readMessageBegin();
      if (msg.type == org.apache.thrift.protocol.TMessageType.EXCEPTION) {
        org.apache.thrift.TApplicationException x = org.apache.thrift.TApplicationException.read(iprot_);
        iprot_.readMessageEnd();
        throw x;
      }
      if (msg.seqid != seqid_) {
        throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.BAD_SEQUENCE_ID, "createAccessAndAccount failed: out of sequence response");
      }
      createAccessAndAccount_result result = new createAccessAndAccount_result();
      result.read(iprot_);
      iprot_.readMessageEnd();
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "createAccessAndAccount failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void createToken(String applicationSecret, String accountId, org.apache.thrift.async.AsyncMethodCallback<createToken_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      createToken_call method_call = new createToken_call(applicationSecret, accountId, resultHandler, this, protocolFactory, transport);
      this.currentMethod = method_call;
      manager.call(method_call);
    }

    public static class createToken_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String applicationSecret;
      private String accountId;
      public createToken_call(String applicationSecret, String accountId, org.apache.thrift.async.AsyncMethodCallback<createToken_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.applicationSecret = applicationSecret;
        this.accountId = accountId;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("createToken", org.apache.thrift.protocol.TMessageType.CALL, 0));
        createToken_args args = new createToken_args();
        args.setApplicationSecret(applicationSecret);
        args.setAccountId(accountId);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public Token getResult() throws org.apache.thrift.TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_createToken();
      }
    }

    public void createAccessAndAccount(String applicationSecret, Access access, String accessToken, String accessSecret, String accessShardId, org.apache.thrift.async.AsyncMethodCallback<createAccessAndAccount_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      createAccessAndAccount_call method_call = new createAccessAndAccount_call(applicationSecret, access, accessToken, accessSecret, accessShardId, resultHandler, this, protocolFactory, transport);
      this.currentMethod = method_call;
      manager.call(method_call);
    }

    public static class createAccessAndAccount_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String applicationSecret;
      private Access access;
      private String accessToken;
      private String accessSecret;
      private String accessShardId;
      public createAccessAndAccount_call(String applicationSecret, Access access, String accessToken, String accessSecret, String accessShardId, org.apache.thrift.async.AsyncMethodCallback<createAccessAndAccount_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.applicationSecret = applicationSecret;
        this.access = access;
        this.accessToken = accessToken;
        this.accessSecret = accessSecret;
        this.accessShardId = accessShardId;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("createAccessAndAccount", org.apache.thrift.protocol.TMessageType.CALL, 0));
        createAccessAndAccount_args args = new createAccessAndAccount_args();
        args.setApplicationSecret(applicationSecret);
        args.setAccess(access);
        args.setAccessToken(accessToken);
        args.setAccessSecret(accessSecret);
        args.setAccessShardId(accessShardId);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public Account getResult() throws org.apache.thrift.TException {
        if (getState() != State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_createAccessAndAccount();
      }
    }

  }

  public static class Processor implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(Iface iface)
    {
      iface_ = iface;
      processMap_.put("createToken", new createToken());
      processMap_.put("createAccessAndAccount", new createAccessAndAccount());
    }

    protected static interface ProcessFunction {
      public void process(int seqid, org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException;
    }

    private Iface iface_;
    protected final HashMap<String,ProcessFunction> processMap_ = new HashMap<String,ProcessFunction>();

    public boolean process(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException
    {
      org.apache.thrift.protocol.TMessage msg = iprot.readMessageBegin();
      ProcessFunction fn = processMap_.get(msg.name);
      if (fn == null) {
        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, org.apache.thrift.protocol.TType.STRUCT);
        iprot.readMessageEnd();
        org.apache.thrift.TApplicationException x = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.UNKNOWN_METHOD, "Invalid method name: '"+msg.name+"'");
        oprot.writeMessageBegin(new org.apache.thrift.protocol.TMessage(msg.name, org.apache.thrift.protocol.TMessageType.EXCEPTION, msg.seqid));
        x.write(oprot);
        oprot.writeMessageEnd();
        oprot.getTransport().flush();
        return true;
      }
      fn.process(msg.seqid, iprot, oprot);
      return true;
    }

    private class createToken implements ProcessFunction {
      public void process(int seqid, org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException
      {
        createToken_args args = new createToken_args();
        try {
          args.read(iprot);
        } catch (org.apache.thrift.protocol.TProtocolException e) {
          iprot.readMessageEnd();
          org.apache.thrift.TApplicationException x = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.PROTOCOL_ERROR, e.getMessage());
          oprot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("createToken", org.apache.thrift.protocol.TMessageType.EXCEPTION, seqid));
          x.write(oprot);
          oprot.writeMessageEnd();
          oprot.getTransport().flush();
          return;
        }
        iprot.readMessageEnd();
        createToken_result result = new createToken_result();
        result.success = iface_.createToken(args.applicationSecret, args.accountId);
        oprot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("createToken", org.apache.thrift.protocol.TMessageType.REPLY, seqid));
        result.write(oprot);
        oprot.writeMessageEnd();
        oprot.getTransport().flush();
      }

    }

    private class createAccessAndAccount implements ProcessFunction {
      public void process(int seqid, org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException
      {
        createAccessAndAccount_args args = new createAccessAndAccount_args();
        try {
          args.read(iprot);
        } catch (org.apache.thrift.protocol.TProtocolException e) {
          iprot.readMessageEnd();
          org.apache.thrift.TApplicationException x = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.PROTOCOL_ERROR, e.getMessage());
          oprot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("createAccessAndAccount", org.apache.thrift.protocol.TMessageType.EXCEPTION, seqid));
          x.write(oprot);
          oprot.writeMessageEnd();
          oprot.getTransport().flush();
          return;
        }
        iprot.readMessageEnd();
        createAccessAndAccount_result result = new createAccessAndAccount_result();
        result.success = iface_.createAccessAndAccount(args.applicationSecret, args.access, args.accessToken, args.accessSecret, args.accessShardId);
        oprot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("createAccessAndAccount", org.apache.thrift.protocol.TMessageType.REPLY, seqid));
        result.write(oprot);
        oprot.writeMessageEnd();
        oprot.getTransport().flush();
      }

    }

  }

  public static class createToken_args implements org.apache.thrift.TBase<createToken_args, createToken_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("createToken_args");

    private static final org.apache.thrift.protocol.TField APPLICATION_SECRET_FIELD_DESC = new org.apache.thrift.protocol.TField("applicationSecret", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField ACCOUNT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("accountId", org.apache.thrift.protocol.TType.STRING, (short)2);

    public String applicationSecret;
    public String accountId;

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      APPLICATION_SECRET((short)1, "applicationSecret"),
      ACCOUNT_ID((short)2, "accountId");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // APPLICATION_SECRET
            return APPLICATION_SECRET;
          case 2: // ACCOUNT_ID
            return ACCOUNT_ID;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments

    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.APPLICATION_SECRET, new org.apache.thrift.meta_data.FieldMetaData("applicationSecret", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING          , "String")));
      tmpMap.put(_Fields.ACCOUNT_ID, new org.apache.thrift.meta_data.FieldMetaData("accountId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING          , "Id")));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(createToken_args.class, metaDataMap);
    }

    public createToken_args() {
    }

    public createToken_args(
      String applicationSecret,
      String accountId)
    {
      this();
      this.applicationSecret = applicationSecret;
      this.accountId = accountId;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public createToken_args(createToken_args other) {
      if (other.isSetApplicationSecret()) {
        this.applicationSecret = other.applicationSecret;
      }
      if (other.isSetAccountId()) {
        this.accountId = other.accountId;
      }
    }

    public createToken_args deepCopy() {
      return new createToken_args(this);
    }

    @Override
    public void clear() {
      this.applicationSecret = null;
      this.accountId = null;
    }

    public String getApplicationSecret() {
      return this.applicationSecret;
    }

    public createToken_args setApplicationSecret(String applicationSecret) {
      this.applicationSecret = applicationSecret;
      return this;
    }

    public void unsetApplicationSecret() {
      this.applicationSecret = null;
    }

    /** Returns true if field applicationSecret is set (has been assigned a value) and false otherwise */
    public boolean isSetApplicationSecret() {
      return this.applicationSecret != null;
    }

    public void setApplicationSecretIsSet(boolean value) {
      if (!value) {
        this.applicationSecret = null;
      }
    }

    public String getAccountId() {
      return this.accountId;
    }

    public createToken_args setAccountId(String accountId) {
      this.accountId = accountId;
      return this;
    }

    public void unsetAccountId() {
      this.accountId = null;
    }

    /** Returns true if field accountId is set (has been assigned a value) and false otherwise */
    public boolean isSetAccountId() {
      return this.accountId != null;
    }

    public void setAccountIdIsSet(boolean value) {
      if (!value) {
        this.accountId = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case APPLICATION_SECRET:
        if (value == null) {
          unsetApplicationSecret();
        } else {
          setApplicationSecret((String)value);
        }
        break;

      case ACCOUNT_ID:
        if (value == null) {
          unsetAccountId();
        } else {
          setAccountId((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case APPLICATION_SECRET:
        return getApplicationSecret();

      case ACCOUNT_ID:
        return getAccountId();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case APPLICATION_SECRET:
        return isSetApplicationSecret();
      case ACCOUNT_ID:
        return isSetAccountId();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof createToken_args)
        return this.equals((createToken_args)that);
      return false;
    }

    public boolean equals(createToken_args that) {
      if (that == null)
        return false;

      boolean this_present_applicationSecret = true && this.isSetApplicationSecret();
      boolean that_present_applicationSecret = true && that.isSetApplicationSecret();
      if (this_present_applicationSecret || that_present_applicationSecret) {
        if (!(this_present_applicationSecret && that_present_applicationSecret))
          return false;
        if (!this.applicationSecret.equals(that.applicationSecret))
          return false;
      }

      boolean this_present_accountId = true && this.isSetAccountId();
      boolean that_present_accountId = true && that.isSetAccountId();
      if (this_present_accountId || that_present_accountId) {
        if (!(this_present_accountId && that_present_accountId))
          return false;
        if (!this.accountId.equals(that.accountId))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(createToken_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      createToken_args typedOther = (createToken_args)other;

      lastComparison = Boolean.valueOf(isSetApplicationSecret()).compareTo(typedOther.isSetApplicationSecret());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetApplicationSecret()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.applicationSecret, typedOther.applicationSecret);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetAccountId()).compareTo(typedOther.isSetAccountId());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAccountId()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accountId, typedOther.accountId);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (field.id) {
          case 1: // APPLICATION_SECRET
            if (field.type == org.apache.thrift.protocol.TType.STRING) {
              this.applicationSecret = iprot.readString();
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case 2: // ACCOUNT_ID
            if (field.type == org.apache.thrift.protocol.TType.STRING) {
              this.accountId = iprot.readString();
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (this.applicationSecret != null) {
        oprot.writeFieldBegin(APPLICATION_SECRET_FIELD_DESC);
        oprot.writeString(this.applicationSecret);
        oprot.writeFieldEnd();
      }
      if (this.accountId != null) {
        oprot.writeFieldBegin(ACCOUNT_ID_FIELD_DESC);
        oprot.writeString(this.accountId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("createToken_args(");
      boolean first = true;

      sb.append("applicationSecret:");
      if (this.applicationSecret == null) {
        sb.append("null");
      } else {
        sb.append(this.applicationSecret);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("accountId:");
      if (this.accountId == null) {
        sb.append("null");
      } else {
        sb.append(this.accountId);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

  }

  public static class createToken_result implements org.apache.thrift.TBase<createToken_result, createToken_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("createToken_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    public Token success;

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments

    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Token.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(createToken_result.class, metaDataMap);
    }

    public createToken_result() {
    }

    public createToken_result(
      Token success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public createToken_result(createToken_result other) {
      if (other.isSetSuccess()) {
        this.success = new Token(other.success);
      }
    }

    public createToken_result deepCopy() {
      return new createToken_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public Token getSuccess() {
      return this.success;
    }

    public createToken_result setSuccess(Token success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((Token)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof createToken_result)
        return this.equals((createToken_result)that);
      return false;
    }

    public boolean equals(createToken_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(createToken_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      createToken_result typedOther = (createToken_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (field.id) {
          case 0: // SUCCESS
            if (field.type == org.apache.thrift.protocol.TType.STRUCT) {
              this.success = new Token();
              this.success.read(iprot);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      oprot.writeStructBegin(STRUCT_DESC);

      if (this.isSetSuccess()) {
        oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
        this.success.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("createToken_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

  }

  public static class createAccessAndAccount_args implements org.apache.thrift.TBase<createAccessAndAccount_args, createAccessAndAccount_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("createAccessAndAccount_args");

    private static final org.apache.thrift.protocol.TField APPLICATION_SECRET_FIELD_DESC = new org.apache.thrift.protocol.TField("applicationSecret", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField ACCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("access", org.apache.thrift.protocol.TType.STRUCT, (short)2);
    private static final org.apache.thrift.protocol.TField ACCESS_TOKEN_FIELD_DESC = new org.apache.thrift.protocol.TField("accessToken", org.apache.thrift.protocol.TType.STRING, (short)3);
    private static final org.apache.thrift.protocol.TField ACCESS_SECRET_FIELD_DESC = new org.apache.thrift.protocol.TField("accessSecret", org.apache.thrift.protocol.TType.STRING, (short)4);
    private static final org.apache.thrift.protocol.TField ACCESS_SHARD_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("accessShardId", org.apache.thrift.protocol.TType.STRING, (short)5);

    public String applicationSecret;
    public Access access;
    public String accessToken;
    public String accessSecret;
    public String accessShardId;

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      APPLICATION_SECRET((short)1, "applicationSecret"),
      ACCESS((short)2, "access"),
      ACCESS_TOKEN((short)3, "accessToken"),
      ACCESS_SECRET((short)4, "accessSecret"),
      ACCESS_SHARD_ID((short)5, "accessShardId");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // APPLICATION_SECRET
            return APPLICATION_SECRET;
          case 2: // ACCESS
            return ACCESS;
          case 3: // ACCESS_TOKEN
            return ACCESS_TOKEN;
          case 4: // ACCESS_SECRET
            return ACCESS_SECRET;
          case 5: // ACCESS_SHARD_ID
            return ACCESS_SHARD_ID;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments

    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.APPLICATION_SECRET, new org.apache.thrift.meta_data.FieldMetaData("applicationSecret", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING          , "String")));
      tmpMap.put(_Fields.ACCESS, new org.apache.thrift.meta_data.FieldMetaData("access", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Access.class)));
      tmpMap.put(_Fields.ACCESS_TOKEN, new org.apache.thrift.meta_data.FieldMetaData("accessToken", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING          , "String")));
      tmpMap.put(_Fields.ACCESS_SECRET, new org.apache.thrift.meta_data.FieldMetaData("accessSecret", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING          , "String")));
      tmpMap.put(_Fields.ACCESS_SHARD_ID, new org.apache.thrift.meta_data.FieldMetaData("accessShardId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING          , "String")));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(createAccessAndAccount_args.class, metaDataMap);
    }

    public createAccessAndAccount_args() {
    }

    public createAccessAndAccount_args(
      String applicationSecret,
      Access access,
      String accessToken,
      String accessSecret,
      String accessShardId)
    {
      this();
      this.applicationSecret = applicationSecret;
      this.access = access;
      this.accessToken = accessToken;
      this.accessSecret = accessSecret;
      this.accessShardId = accessShardId;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public createAccessAndAccount_args(createAccessAndAccount_args other) {
      if (other.isSetApplicationSecret()) {
        this.applicationSecret = other.applicationSecret;
      }
      if (other.isSetAccess()) {
        this.access = new Access(other.access);
      }
      if (other.isSetAccessToken()) {
        this.accessToken = other.accessToken;
      }
      if (other.isSetAccessSecret()) {
        this.accessSecret = other.accessSecret;
      }
      if (other.isSetAccessShardId()) {
        this.accessShardId = other.accessShardId;
      }
    }

    public createAccessAndAccount_args deepCopy() {
      return new createAccessAndAccount_args(this);
    }

    @Override
    public void clear() {
      this.applicationSecret = null;
      this.access = null;
      this.accessToken = null;
      this.accessSecret = null;
      this.accessShardId = null;
    }

    public String getApplicationSecret() {
      return this.applicationSecret;
    }

    public createAccessAndAccount_args setApplicationSecret(String applicationSecret) {
      this.applicationSecret = applicationSecret;
      return this;
    }

    public void unsetApplicationSecret() {
      this.applicationSecret = null;
    }

    /** Returns true if field applicationSecret is set (has been assigned a value) and false otherwise */
    public boolean isSetApplicationSecret() {
      return this.applicationSecret != null;
    }

    public void setApplicationSecretIsSet(boolean value) {
      if (!value) {
        this.applicationSecret = null;
      }
    }

    public Access getAccess() {
      return this.access;
    }

    public createAccessAndAccount_args setAccess(Access access) {
      this.access = access;
      return this;
    }

    public void unsetAccess() {
      this.access = null;
    }

    /** Returns true if field access is set (has been assigned a value) and false otherwise */
    public boolean isSetAccess() {
      return this.access != null;
    }

    public void setAccessIsSet(boolean value) {
      if (!value) {
        this.access = null;
      }
    }

    public String getAccessToken() {
      return this.accessToken;
    }

    public createAccessAndAccount_args setAccessToken(String accessToken) {
      this.accessToken = accessToken;
      return this;
    }

    public void unsetAccessToken() {
      this.accessToken = null;
    }

    /** Returns true if field accessToken is set (has been assigned a value) and false otherwise */
    public boolean isSetAccessToken() {
      return this.accessToken != null;
    }

    public void setAccessTokenIsSet(boolean value) {
      if (!value) {
        this.accessToken = null;
      }
    }

    public String getAccessSecret() {
      return this.accessSecret;
    }

    public createAccessAndAccount_args setAccessSecret(String accessSecret) {
      this.accessSecret = accessSecret;
      return this;
    }

    public void unsetAccessSecret() {
      this.accessSecret = null;
    }

    /** Returns true if field accessSecret is set (has been assigned a value) and false otherwise */
    public boolean isSetAccessSecret() {
      return this.accessSecret != null;
    }

    public void setAccessSecretIsSet(boolean value) {
      if (!value) {
        this.accessSecret = null;
      }
    }

    public String getAccessShardId() {
      return this.accessShardId;
    }

    public createAccessAndAccount_args setAccessShardId(String accessShardId) {
      this.accessShardId = accessShardId;
      return this;
    }

    public void unsetAccessShardId() {
      this.accessShardId = null;
    }

    /** Returns true if field accessShardId is set (has been assigned a value) and false otherwise */
    public boolean isSetAccessShardId() {
      return this.accessShardId != null;
    }

    public void setAccessShardIdIsSet(boolean value) {
      if (!value) {
        this.accessShardId = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case APPLICATION_SECRET:
        if (value == null) {
          unsetApplicationSecret();
        } else {
          setApplicationSecret((String)value);
        }
        break;

      case ACCESS:
        if (value == null) {
          unsetAccess();
        } else {
          setAccess((Access)value);
        }
        break;

      case ACCESS_TOKEN:
        if (value == null) {
          unsetAccessToken();
        } else {
          setAccessToken((String)value);
        }
        break;

      case ACCESS_SECRET:
        if (value == null) {
          unsetAccessSecret();
        } else {
          setAccessSecret((String)value);
        }
        break;

      case ACCESS_SHARD_ID:
        if (value == null) {
          unsetAccessShardId();
        } else {
          setAccessShardId((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case APPLICATION_SECRET:
        return getApplicationSecret();

      case ACCESS:
        return getAccess();

      case ACCESS_TOKEN:
        return getAccessToken();

      case ACCESS_SECRET:
        return getAccessSecret();

      case ACCESS_SHARD_ID:
        return getAccessShardId();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case APPLICATION_SECRET:
        return isSetApplicationSecret();
      case ACCESS:
        return isSetAccess();
      case ACCESS_TOKEN:
        return isSetAccessToken();
      case ACCESS_SECRET:
        return isSetAccessSecret();
      case ACCESS_SHARD_ID:
        return isSetAccessShardId();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof createAccessAndAccount_args)
        return this.equals((createAccessAndAccount_args)that);
      return false;
    }

    public boolean equals(createAccessAndAccount_args that) {
      if (that == null)
        return false;

      boolean this_present_applicationSecret = true && this.isSetApplicationSecret();
      boolean that_present_applicationSecret = true && that.isSetApplicationSecret();
      if (this_present_applicationSecret || that_present_applicationSecret) {
        if (!(this_present_applicationSecret && that_present_applicationSecret))
          return false;
        if (!this.applicationSecret.equals(that.applicationSecret))
          return false;
      }

      boolean this_present_access = true && this.isSetAccess();
      boolean that_present_access = true && that.isSetAccess();
      if (this_present_access || that_present_access) {
        if (!(this_present_access && that_present_access))
          return false;
        if (!this.access.equals(that.access))
          return false;
      }

      boolean this_present_accessToken = true && this.isSetAccessToken();
      boolean that_present_accessToken = true && that.isSetAccessToken();
      if (this_present_accessToken || that_present_accessToken) {
        if (!(this_present_accessToken && that_present_accessToken))
          return false;
        if (!this.accessToken.equals(that.accessToken))
          return false;
      }

      boolean this_present_accessSecret = true && this.isSetAccessSecret();
      boolean that_present_accessSecret = true && that.isSetAccessSecret();
      if (this_present_accessSecret || that_present_accessSecret) {
        if (!(this_present_accessSecret && that_present_accessSecret))
          return false;
        if (!this.accessSecret.equals(that.accessSecret))
          return false;
      }

      boolean this_present_accessShardId = true && this.isSetAccessShardId();
      boolean that_present_accessShardId = true && that.isSetAccessShardId();
      if (this_present_accessShardId || that_present_accessShardId) {
        if (!(this_present_accessShardId && that_present_accessShardId))
          return false;
        if (!this.accessShardId.equals(that.accessShardId))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(createAccessAndAccount_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      createAccessAndAccount_args typedOther = (createAccessAndAccount_args)other;

      lastComparison = Boolean.valueOf(isSetApplicationSecret()).compareTo(typedOther.isSetApplicationSecret());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetApplicationSecret()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.applicationSecret, typedOther.applicationSecret);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetAccess()).compareTo(typedOther.isSetAccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.access, typedOther.access);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetAccessToken()).compareTo(typedOther.isSetAccessToken());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAccessToken()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accessToken, typedOther.accessToken);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetAccessSecret()).compareTo(typedOther.isSetAccessSecret());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAccessSecret()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accessSecret, typedOther.accessSecret);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetAccessShardId()).compareTo(typedOther.isSetAccessShardId());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetAccessShardId()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accessShardId, typedOther.accessShardId);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (field.id) {
          case 1: // APPLICATION_SECRET
            if (field.type == org.apache.thrift.protocol.TType.STRING) {
              this.applicationSecret = iprot.readString();
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case 2: // ACCESS
            if (field.type == org.apache.thrift.protocol.TType.STRUCT) {
              this.access = new Access();
              this.access.read(iprot);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case 3: // ACCESS_TOKEN
            if (field.type == org.apache.thrift.protocol.TType.STRING) {
              this.accessToken = iprot.readString();
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case 4: // ACCESS_SECRET
            if (field.type == org.apache.thrift.protocol.TType.STRING) {
              this.accessSecret = iprot.readString();
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case 5: // ACCESS_SHARD_ID
            if (field.type == org.apache.thrift.protocol.TType.STRING) {
              this.accessShardId = iprot.readString();
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (this.applicationSecret != null) {
        oprot.writeFieldBegin(APPLICATION_SECRET_FIELD_DESC);
        oprot.writeString(this.applicationSecret);
        oprot.writeFieldEnd();
      }
      if (this.access != null) {
        oprot.writeFieldBegin(ACCESS_FIELD_DESC);
        this.access.write(oprot);
        oprot.writeFieldEnd();
      }
      if (this.accessToken != null) {
        oprot.writeFieldBegin(ACCESS_TOKEN_FIELD_DESC);
        oprot.writeString(this.accessToken);
        oprot.writeFieldEnd();
      }
      if (this.accessSecret != null) {
        oprot.writeFieldBegin(ACCESS_SECRET_FIELD_DESC);
        oprot.writeString(this.accessSecret);
        oprot.writeFieldEnd();
      }
      if (this.accessShardId != null) {
        oprot.writeFieldBegin(ACCESS_SHARD_ID_FIELD_DESC);
        oprot.writeString(this.accessShardId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("createAccessAndAccount_args(");
      boolean first = true;

      sb.append("applicationSecret:");
      if (this.applicationSecret == null) {
        sb.append("null");
      } else {
        sb.append(this.applicationSecret);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("access:");
      if (this.access == null) {
        sb.append("null");
      } else {
        sb.append(this.access);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("accessToken:");
      if (this.accessToken == null) {
        sb.append("null");
      } else {
        sb.append(this.accessToken);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("accessSecret:");
      if (this.accessSecret == null) {
        sb.append("null");
      } else {
        sb.append(this.accessSecret);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("accessShardId:");
      if (this.accessShardId == null) {
        sb.append("null");
      } else {
        sb.append(this.accessShardId);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

  }

  public static class createAccessAndAccount_result implements org.apache.thrift.TBase<createAccessAndAccount_result, createAccessAndAccount_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("createAccessAndAccount_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    public Account success;

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments

    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Account.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(createAccessAndAccount_result.class, metaDataMap);
    }

    public createAccessAndAccount_result() {
    }

    public createAccessAndAccount_result(
      Account success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public createAccessAndAccount_result(createAccessAndAccount_result other) {
      if (other.isSetSuccess()) {
        this.success = new Account(other.success);
      }
    }

    public createAccessAndAccount_result deepCopy() {
      return new createAccessAndAccount_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public Account getSuccess() {
      return this.success;
    }

    public createAccessAndAccount_result setSuccess(Account success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((Account)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof createAccessAndAccount_result)
        return this.equals((createAccessAndAccount_result)that);
      return false;
    }

    public boolean equals(createAccessAndAccount_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(createAccessAndAccount_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      createAccessAndAccount_result typedOther = (createAccessAndAccount_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (field.id) {
          case 0: // SUCCESS
            if (field.type == org.apache.thrift.protocol.TType.STRUCT) {
              this.success = new Account();
              this.success.read(iprot);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      oprot.writeStructBegin(STRUCT_DESC);

      if (this.isSetSuccess()) {
        oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
        this.success.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("createAccessAndAccount_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

  }

}
